name: Build for Linux
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    outputs:
      wheel_name:
        description: "Wheel name"
        value: ${{ jobs.build-wheel.outputs.name }}

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.whl_name.outputs.whl_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker run --rm -v `pwd`:/replicat -w /replicat quay.io/pypa/manylinux2014_x86_64 bash -c \
             'python${{ inputs.python-version }} -m build --wheel && \
             auditwheel repair dist/*.whl --plat manylinux2014_x86_64 --wheel-dir manylinux/'
      - run: echo "WHEEL_NAME=$(basename $(ls manylinux/*.whl))" >> $GITHUB_ENV
      - id: whl_name
        run: echo "::set-output name=whl_name::${{ env.WHEEL_NAME }}"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WHEEL_NAME }}
          path: manylinux/${{ env.WHEEL_NAME }}
